### PR TITLE
hellen's createAccount with my style changes

### PR DESCRIPTION
**Pull request by nrs32**

### CODE REVIEW

**Comment by sz4321** [comment]
Screen Shot 2019-10-10 at 6 15 17 PM

**Comment by sambridhi35** [comment]
Screen Shot 2019-10-20 at 4 31 57 PM

**Comment by sambridhi35** [comment]
Screen Shot 2019-10-24 at 7 33 38 PM

**Comment by sz4321** [comment]
database_schema

**Comment by sz4321** [comment]
database_schema

**Comment by sambridhi35** [comment]
Screen Shot 2019-12-11 at 7 24 41 PM

**Pull request merged**
